name: Run Tests on MASTER Branch Commit
on: 
    push:
        branches:
            - master

jobs: 
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup dotnet 8.0.X
              uses: actions/setup-dotnet@v3
              with: 
                dotnet-version: 8.0.x
            
            - name: Install Dependencies
              run: dotnet restore
      
            - name: Build
              run: dotnet build
      
            - name: Run Test Suite
              working-directory: ./DotnetHoneyApi.Tests
              run: dotnet test